feat: createFacebookOAuth2Client
denoland/deno_kv_oauth pull request #94
Opened 2023-06-16 14:44 UTC by j3lte

Reference: #42

2023-06-16 14:48 UTC, lino-levan requested changes

2023-06-16 14:48 UTC, lino-levan commented on src/create_oauth2_client.ts
> + * Requires `--allow-env[=GITHUB_CLIENT_ID,GITHUB_CLIENT_SECRET]` permissions and environment variables:
```suggestion
 * Requires `--allow-env[=FACEBOOK_CLIENT_ID,FACEBOOK_CLIENT_SECRET]` permissions and environment variables:
```

2023-06-17 00:30 UTC, iuioiua requested changes
Nice! Can you please run `deno fmt`?

2023-06-17 07:43 UTC, iuioiua approved these changes
LGTM! Thank you, @j3lte!

2023-06-17 07:43 UTC, merged